var baselayers = {
  "umd_tree_loss_gain": {
    "id": 597,
    "slug": "umd_tree_loss_gain",
    "title": "UMD tree cover\nloss",
    "title_color": "#F69",
    "subtitle": "",
    "sublayer": "",
    "table_name": "",
    "source": "",
    "category_color": "#F69",
    "category_slug": "forest_clearing",
    "category_name": "Forest change",
    "external": "false",
    "zmin": "",
    "zmax": "",
    "mindate": "2001-01-01T12:00:00.000Z",
    "maxdate": "2013-12-31T12:00:00.000Z",
    "xmax": null,
    "xmin": null,
    "ymax": null,
    "ymin": null,
    "tileurl": "",
    "visible": true,
    "position": 1,
    "detailsTpl": "\n  <div class=\"layer-details\">\n    <p class=\"canopy\" title=\"Click the gear icon to change the tree cover canopy density\">Displaying loss with ><span> 10</span>% canopy density.</p>\n  </div>\n\n"
  },
  "forestgain": {
    "id": 596,
    "slug": "forestgain",
    "title": "UMD tree cover gain",
    "title_color": "#6D6DE5",
    "subtitle": "(12 years, 30m, global)",
    "sublayer": "",
    "table_name": "forestgain",
    "source": "",
    "category_color": "#F69",
    "category_slug": "forest_clearing",
    "category_name": "Forest change",
    "external": "true",
    "zmin": "",
    "zmax": "",
    "mindate": null,
    "maxdate": null,
    "xmax": null,
    "xmin": null,
    "ymax": null,
    "ymin": null,
    "tileurl": "https://earthengine.google.org/static/hansen_2013/gain_alpha/{Z}/{X}/{Y}.png",
    "visible": true,
    "position": 0,
    "detailsTpl": "\n  <div class=\"layer-details\">\n    \n  </div>\n\n"
  }
};
