export default {
  title: {
    withLocation: 'Deforestation Alerts in {location}'
  },
  config: {
    size: 'large',
    categories: ['summary', 'forest-change'],
    weeks: [13, 26, 52],
    admins: ['country', 'region', 'subRegion'],
    type: 'loss',
    selectors: ['weeks'],
    metaKey: 'widget_deforestation_graph',
    interactive: true,
    locationWhitelist: [
      'ABW',
      'AGO',
      'AIA',
      'ARG',
      'ATG',
      'AUS',
      'BDI',
      'BEN',
      'BES',
      'BFA',
      'BGD',
      'BHS',
      'BLM',
      'BLZ',
      'BOL',
      'BRA',
      'BRB',
      'BRN',
      'BTN',
      'BWA',
      'CAF',
      'CHL',
      'CHN',
      'CIV',
      'CMR',
      'COD',
      'COG',
      'COL',
      'COM',
      'CRI',
      'CUB',
      'CUW',
      'CYM',
      'DMA',
      'DOM',
      'ECU',
      'EGY',
      'ERI',
      'ESP',
      'ETH',
      'FJI',
      'GAB',
      'GHA',
      'GIN',
      'GLP',
      'GMB',
      'GNB',
      'GNQ',
      'GRD',
      'GTM',
      'GUF',
      'GUY',
      'HKG',
      'HND',
      'HTI',
      'IDN',
      'IND',
      'IRN',
      'JAM',
      'JPN',
      'KEN',
      'KHM',
      'KNA',
      'LAO',
      'LBR',
      'LCA',
      'LKA',
      'LSO',
      'MAC',
      'MAF',
      'MDG',
      'MEX',
      'MLI',
      'MMR',
      'MOZ',
      'MSR',
      'MTQ',
      'MUS',
      'MWI',
      'MYS',
      'MYT',
      'NAM',
      'NCL',
      'NER',
      'NGA',
      'NIC',
      'NPL',
      'OMN',
      'PAK',
      'PAN',
      'PER',
      'PHL',
      'PLW',
      'PNG',
      'PRI',
      'PRY',
      'REU',
      'RWA',
      'SDN',
      'SEN',
      'SGP',
      'SLB',
      'SLE',
      'SLV',
      'SOM',
      'SSD',
      'SUR',
      'SWZ',
      'SXM',
      'SYC',
      'TCA',
      'TCD',
      'TGO',
      'THA',
      'TLS',
      'TTO',
      'TWN',
      'TZA',
      'UGA',
      'USA',
      'VCT',
      'VEN',
      'VGB',
      'VIR',
      'VNM',
      'VUT',
      'YEM',
      'ZAF',
      'ZMB',
      'ZWE'
    ],
    layers: ['umd_as_it_happens'],
    sortOrder: {
      summary: 6,
      forestChange: 9
    },
    sentences: {
      initial:
        'There were {count} GLAD alerts reported in the week of the {date}. This was {status} compared to the same week in previous years.'
    }
  },
  settings: {
    period: 'week',
    weeks: 13,
    layers: ['umd_as_it_happens'],
    layerStartDate: null,
    layerEndDate: null
  },
  enabled: true
};
