export default {
  title: {
    withLocation: 'Fire Alerts in {location}'
  },
  config: {
    size: 'large',
    categories: ['summary', 'forest-change'],
    weeks: [13, 26, 52],
    admins: ['country', 'region', 'subRegion'],
    type: 'fires',
    selectors: ['weeks', 'datasets'],
    metaKey: 'widget_fire_alert_location',
    interactive: true,
    locationWhitelist: [
      'IDN',
      'MEX',
      'AUS',
      'THA',
      'MMR',
      'KHM',
      'MWI',
      'CMR',
      'GAB',
      'COG',
      'COD',
      'FIN',
      'RUS',
      'NGA',
      'GNQ',
      'AGO',
      'NOR',
      'TZA',
      'IRN',
      'MAR',
      'ETH',
      'KEN',
      'UKR',
      'DZA',
      'ESP',
      'GRC',
      'LTU',
      'SSD',
      'EGY',
      'MLI',
      'SAU',
      'BLR',
      'GEO',
      'GHA',
      'SJM',
      'BFA',
      'NER',
      'ITA',
      'SEN',
      'FRA',
      'ROU',
      'TUN',
      'KAZ',
      'LVA',
      'STP',
      'POL',
      'HRV',
      'ARM',
      'JOR',
      'ESH',
      'PRT',
      'IRQ',
      'MRT',
      'TKM',
      'AZE',
      'ERI',
      'ZMB',
      'TUR',
      'BEN',
      'BGR',
      'SOM',
      'SYR',
      'SDN',
      'AUT',
      'CYP',
      'TCD',
      'SVN',
      'CZE',
      'YEM',
      'LBY',
      'KWT',
      'ALB',
      'SRB',
      'MKD',
      'SGS',
      'UGA',
      'MNE',
      'OMN',
      'BIH',
      'UZB',
      'GRL',
      'MDA',
      'TGO',
      'NAM',
      'EST',
      'BRA',
      'GMB',
      'CIV',
      'QAT',
      'ARE',
      'CAF',
      'IND',
      'XNC',
      'DEU',
      'DJI',
      'AFG',
      'ISR',
      'PAK',
      'AND',
      'CHE',
      'GNB',
      'XKO',
      'LBN',
      'CAN',
      'ZWE',
      'BHR',
      'ARG',
      'VEN',
      'MLT',
      'GIN',
      'COL',
      'GUF',
      'PER',
      'MDG',
      'SHN',
      'GBR',
      'HUN',
      'PRY',
      'SUR',
      'SWE',
      'ZAF',
      'CPV',
      'GIB',
      'CUB',
      'MOZ',
      'BOL',
      'TJK',
      'USA',
      'CHN',
      'HND',
      'IRL',
      'SYC',
      'BDI',
      'CHL',
      'ISL',
      'LSO',
      'NIC',
      'RWA',
      'SVK',
      'URY'
    ],
    sortOrder: {
      summary: 100,
      forestChange: 100
    },
    sentences: {
      initial:
        'There were {count} {dataset} fire alerts reported in the week of the {date}. This was {status} compared to the same week in previous years.'
    }
  },
  settings: {
    period: 'week',
    weeks: 13,
    dataset: 'MODIS',
    layerStartDate: null,
    layerEndDate: null
  },
  enabled: true
};
