export default {
  widget: 'primaryForest',
  title: 'Primary forest in {location}',
  categories: ['land-cover'],
  types: ['country'],
  admins: ['adm0', 'adm1', 'adm2'],
  options: {
    landCategories: true,
    thresholds: true
  },
  colors: 'extent',
  metaKey: 'widget_primary_forest',
  datasets: [
    // tree cover
    {
      dataset: '044f4af8-be72-4999-b7dd-13434fc4a394',
      layers: {
        2010: '78747ea1-34a9-4aa7-b099-bdb8948200f4',
        2000: 'c05c32fd-289c-4b20-8d73-dc2458234e04'
      }
    }
  ],
  sortOrder: {
    landCover: 4
  },
  sentences: {
    initial:
      'As of 2001, {percentage} of {location} total tree cover was <b>primary forest</b>.',
    withIndicator:
      'As of 2001, {percentage} of {location} total tree cover in {indicator} was <b>primary forest</b>.'
  },
  whitelists: {
    adm0: [
      'IDN',
      'BRA',
      'MYS',
      'COL',
      'PER',
      'IND',
      'MMR',
      'VNM',
      'VEN',
      'CMR',
      'MEX',
      'BOL',
      'PAN',
      'ECU',
      'COG',
      'KHM',
      'COD',
      'THA',
      'LAO',
      'BTN',
      'PHL',
      'GAB',
      'CRI',
      'ARG',
      'PNG',
      'SUR',
      'GUY',
      'CHN',
      'GTM',
      'GUF',
      'HND',
      'NPL',
      'TZA',
      'NIC',
      'KEN',
      'GNQ',
      'MDG',
      'ZAF',
      'CUB',
      'PRY',
      'LBR',
      'CAF',
      'LKA',
      'DOM',
      'BRN',
      'BLZ',
      'SLB',
      'UGA',
      'CIV',
      'NGA',
      'AGO',
      'ETH',
      'TWN',
      'GNB',
      'BGD',
      'USA',
      'FJI',
      'PRI',
      'TTO',
      'VUT',
      'GIN',
      'JAM',
      'SLE',
      'MOZ',
      'RWA',
      'SLV',
      'ZMB',
      'GHA',
      'GLP',
      'CYM',
      'DMA',
      'AUS',
      'BHS',
      'HTI',
      'SEN',
      'MWI',
      'TCA',
      'PLW',
      'LCA',
      'MTQ',
      'ZWE',
      'VCT',
      'SSD',
      'VGB',
      'VIR',
      'GMB',
      'BDI',
      'SGP',
      'BEN',
      'MSR',
      'COM',
      'KNA',
      'MAF',
      'BES',
      'TGO',
      'ABW',
      'MDV',
      'ATG',
      'TLS',
      'SXM',
      'LSO',
      'AIA',
      'CHL',
      'CUW',
      'UMI',
      'GRD'
    ]
  }
};
