export const sectors = {
  'Government/Public Sector': [
    'Forest Management/Park Management',
    'Law Enforcement',
    'Legislature/Parliament',
    'Ministry/National Agency',
    'Subnational Agency',
    'Other:',
  ],
  'Philantropic Organization': [
    'Director/Executive',
    'Project/Program Manager',
    'Researcher',
    'Monitoring/Evaluation',
    'Field/Country Staff',
    'Other:',
  ],
  'NGO - National or Local': [
    'Director/Executive',
    'Project/Program Manager',
    'Monitoring/Evaluation Specialist',
    'GIS/Technical Specialist',
    'Researcher',
    'Field Staff',
    'Communications Specialist',
    'Park/Forest Ranger',
    'Other:',
  ],
  'NGO - International': [
    'Director/Executive',
    'Project/Program Manager',
    'Monitoring/Evaluation Specialist',
    'GIS/Technical Specialist',
    'Field/Country Staff',
    'Communications Specialist',
    'Researcher',
    'Other:',
  ],
  'Intergovernmental/Multilateral Organization': [
    'Director/Executive',
    'Project/Program Manager',
    'Researcher',
    'Field/Country Staff',
    'Monitoring/Evaluation Specialist',
    'GIS/Technical Specialist',
    'Communications Specialist',
    'Other:',
  ],
  'Academic/Research Organization': [
    'Faculty (Primary/Secondary)',
    'Faculty (University)',
    'Student (Primary/Secondary)',
    'Student (University/Graduate)',
    'Researcher (Post-Doc, Fellow, etc.)',
    'Other:',
  ],
  'Journalist/Media Organization': ['Reporter', 'Editor', 'Other:'],
  'Indigenous or Community-Based Organization': [
    'Community Leader',
    'Forest Manager/Monitor',
    'GIS/Technical Specialist',
    'Communications Specialist',
    'Other:',
  ],
  'Business/Private sector': [
    'Supply Chain Manager',
    'Supply Chain Analyst',
    'Procurement Staff',
    'Retailer/Trader',
    'Land or Concession Owner',
    'Other:',
  ],
  'No Affiliation': ['Other:'],
  'Other (Write In)': ['Other:'],
};

export const interests = [
  'Innovations in Monitoring',
  'Fires',
  'Forest Watcher Mobile App',
  'Climate and Carbon',
  'Biodiversity',
  'Agricultural Supply Chains',
  'Small Grants Fund and Tech Fellowship',
  'Landscape Restoration',
  'GFW Users in Action',
  'Places to Watch alerts',
  'Deforestation',
];

export const howDoYouUse = [
  'Monitor or manage an area',
  'Plan field work (patrols/investigations)',
  'Identify illegal activity',
  'Advocacy/campaigning',
  'Land use planning/land use allocation',
  'Inform grant funding decisions/results-based payments',
  'Monitor results/impacts',
  'General research',
  'Data or visuals for blogs or media stories',
  'Data or visuals for presentations and reports',
  'Learn about forests/my country',
  'Inform purchasing/procurement/investment decisions',
  'Educational support materials',
  'Not sure; new to GFW',
];

export const topics = [
  'Agricultural Supply Chains',
  'Climate and Biodiversity',
  'Fires',
  'Forest Watcher Mobile App',
  'Innovations in Monitoring',
  'Small Grants Fund and Tech Fellowship',
];

export const preferredLanguages = [
  { label: 'English', value: 'en' },
  { label: 'Français', value: 'fr' },
  { label: 'Español', value: 'es' },
  { label: 'Português', value: 'pt' },
  { label: 'Bahasa Indonesia', value: 'id' },
];
