export default {
  title: {
    withLocation: 'Location of deforestation Alerts in {location}'
  },
  config: {
    size: 'small',
    units: ['ha', '%'],
    categories: ['forest-change'],
    admins: ['country', 'region'],
    selectors: [
      'forestTypes',
      'landCategories',
      'thresholds',
      'units',
      'extentYears',
      'weeks'
    ],
    metaKey: 'widget_deforestation_alert_location',
    locationWhitelist: [
      'ABW',
      'AGO',
      'AIA',
      'ARG',
      'ATG',
      'AUS',
      'BDI',
      'BEN',
      'BES',
      'BFA',
      'BGD',
      'BHS',
      'BLM',
      'BLZ',
      'BOL',
      'BRA',
      'BRB',
      'BRN',
      'BTN',
      'BWA',
      'CAF',
      'CHL',
      'CHN',
      'CIV',
      'CMR',
      'COD',
      'COG',
      'COL',
      'COM',
      'CRI',
      'CUB',
      'CUW',
      'CYM',
      'DMA',
      'DOM',
      'ECU',
      'EGY',
      'ERI',
      'ESP',
      'ETH',
      'FJI',
      'GAB',
      'GHA',
      'GIN',
      'GLP',
      'GMB',
      'GNB',
      'GNQ',
      'GRD',
      'GTM',
      'GUF',
      'GUY',
      'HKG',
      'HND',
      'HTI',
      'IDN',
      'IND',
      'IRN',
      'JAM',
      'JPN',
      'KEN',
      'KHM',
      'KNA',
      'LAO',
      'LBR',
      'LCA',
      'LKA',
      'LSO',
      'MAC',
      'MAF',
      'MDG',
      'MEX',
      'MLI',
      'MMR',
      'MOZ',
      'MSR',
      'MTQ',
      'MUS',
      'MWI',
      'MYS',
      'MYT',
      'NAM',
      'NCL',
      'NER',
      'NGA',
      'NIC',
      'NPL',
      'OMN',
      'PAK',
      'PAN',
      'PER',
      'PHL',
      'PLW',
      'PNG',
      'PRI',
      'PRY',
      'REU',
      'RWA',
      'SDN',
      'SEN',
      'SGP',
      'SLB',
      'SLE',
      'SLV',
      'SOM',
      'SSD',
      'SUR',
      'SWZ',
      'SXM',
      'SYC',
      'TCA',
      'TCD',
      'TGO',
      'THA',
      'TLS',
      'TTO',
      'TWN',
      'TZA',
      'UGA',
      'USA',
      'VCT',
      'VEN',
      'VGB',
      'VIR',
      'VNM',
      'VUT',
      'YEM',
      'ZAF',
      'ZMB',
      'ZWE'
    ],
    locationCheck: true,
    type: 'loss',
    layers: ['umd_as_it_happens'],
    sortOrder: {
      summary: 6,
      forestChange: 10
    },
    sentences: {
      initial:
        'In the last {timeframe} in {location}, {count} GLAD alerts were detected, which affected an area of approximately {area}. The top {topRegions} accounted for {topPercent} of all GLAD alerts.',
      withInd:
        'In the last {timeframe} in {location}, {count} GLAD alerts were detected within {indicator}, which affected an area of approximately {area}. The top {topRegions} accounted for {topPercent} of all GLAD alerts.'
    }
  },
  settings: {
    threshold: 30,
    extentYear: 2010,
    unit: '%',
    weeks: 4,
    pageSize: 5,
    page: 0,
    layers: ['umd_as_it_happens']
  },
  enabled: true
};
